server {
    listen 80;
    server_name maximka.ru; # <-- Твой домен

    # Важно для Certbot: пробрасываем папку для проверки
    # Certbot будет класть сюда файл, Nginx будет его отдавать, Let's Encrypt проверит
    location /.well-known/acme-challenge/ {
        root /var/www/certbot;
    }

    location / {
        root /usr/share/nginx/html;
        index index.html;
        try_files $uri $uri/ /index.html;
    }

    # Секция для API (можно пока оставить или временно убрать, если не будет работать Certbot)
    location /api/ {
        proxy_pass http://api:8080;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_set_header Host $host;
        proxy_cache_bypass $http_upgrade;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}