name: Deploy to Production

on:
  push:
    branches: [ master ] # ��������� ��� ���� � ����� main

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push API
        uses: docker/build-push-action@v4
        with:
          # ���� � �����, ��� ����� Dockerfile �������
          context: ./UserCrud
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/usercrud-api:latest

      - name: Build and push Frontend
        uses: docker/build-push-action@v4
        with:
          context: ./usercrud.client
          file: ./usercrud.client/Dockerfile.prod
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/usercrud-frontend:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build-and-push
    steps:
      - name: Checkout code (for SSH file transfer)
        uses: actions/checkout@v3

      - name: Deploy via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          password: ${{ secrets.SSH_PASSWORD }}
          source: "docker-compose.prod.yml,nginx/prod.conf,nginx/certbot/www,nginx/certbot/conf"
          target: "/usercrud/UserCrud"
          script: |
            cd /usercrud/UserCrud
            rm -f docker-compose.prod.yml
            rm -f nginx/prod.conf
            docker compose -f docker-compose.prod.yml pull
            docker compose -f docker-compose.prod.yml up -d --force-recreate frontend
            docker image prune -f

      - name: Complete job
        run: echo "Job completed successfully."